# Generated by Django 4.0.5 on 2022-06-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50)),
                ('price_usd', models.CharField(max_length=50)),
                ('price_rub', models.CharField(max_length=50)),
                ('delivery_time', models.CharField(max_length=50)),
            ],
        ),
    ]
