# Generated by Django 4.0.5 on 2022-06-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.CharField(max_length=50, verbose_name='время поставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.CharField(max_length=50, verbose_name='заказ №'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_rub',
            field=models.CharField(max_length=50, verbose_name='стоимость руб'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_usd',
            field=models.CharField(max_length=50, verbose_name='стоимость $'),
        ),
    ]
