# Generated by Django 4.0.5 on 2022-06-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_orders_delivery_time_alter_orders_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_num',
        ),
    ]
